### ISSUE TITLE
Reported Results 

### ISSUE THREAD

**Issue by debasmitdas** [lzrobots/DeepEmbeddingModel_ZSL#1]
Hi, I am trying to reproduce your results. I wait till all the iterations are completed and note the final result. However, the results do not exactly match or are very close to that reported in the home page of this Github repository. I know this can happen due to the random initialization strategy of neural networks. But, how do I get results which are sufficiently close to the reported ones. Do you use early stopping, which is not actually present in the code ? Kindly help. (I am talking about the *_GBU.py scripts)

**Comment by lzrobots** [comment]
@debasmitdas Hi, yes we use early stopping.

**Comment by debasmitdas** [comment]
Hi,
But the early stopping seems to be not implemented in the code. Also, I guess there is no validation data to carry out early stopping.  Can you kindly correct me if I am wrong ?

**Comment by lzrobots** [comment]
@debasmitdas you are right but we don't set validation in our current version code as we don't have much hyper-parameters to tune. please don't wait until the last iteration.
