### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by GanAndreas** [lzrobots/DeepEmbeddingModel_ZSL#2]
Hi, I'm new in Zero_shot Learning and i'm facing a problem here

I tried to implement the AwA_Attribute.py

and I get this respond:

File "AwA_attribute.py", line 125, in <module>
att_batch_val, visual_batch_val = iter_.next()
AttributeError: 'generator' object has no attribute 'next'

**Comment by drcege** [comment]
@GanAndreas  Maybe python2 instead of python3

**Comment by GanAndreas** [comment]
yes, I already found that problem.
I'm using anaconda
already tried to install python 2,7
but when I install the tensorflow 1.1.0, it would replace the python into 3.6.7

**Comment by drcege** [comment]
I have successfully run the code without error.
After creating a new python environment using conda, install tensorflow by pip.
Like this:
<pre>
conda create -n <b>your_env_name</b>  pip python=2.7
source activate <b>your_env_name</b>
pip install --ignore-installed --upgrade <a href="https://www.tensorflow.org/install/pip#package-location" title=tensorflow_url_for_py2.7>tensorflow_url_for_py2.7</a><pre>

**Comment by GanAndreas** [comment]
oooh i see.
I tried on windows before
thanks alot mate!
Cheers
